### ISSUE TITLE
Presets dont work

### ISSUE THREAD

**Issue by Ostrich21** [joaoh1/OkZoomer#105]
Whenever i try to select a preset, when i go off the pause menu, it automaticly goes back to deafult. I cant seem to find any apply button or something. Sorry if im being daft but im just really confused.

**Comment by EnnuiL** [comment]
Oh wait! So, the apply button is the "Reset Settings" button right next to the preset button;
![The Presets section, with the "Preset" option set to Default and a "Reset Settings" button next to it](https://github.com/Up-Mods/OkZoomer/assets/85590273/5940987d-e1a6-401f-be2a-ad5ba07539ce)
I thought exiting through ESC was discarding changes, but I apparently made it so that it saved anyway; Maybe I should rename "Reset Settings" to "Apply Preset"?

**Comment by UpcraftLP** [comment]
fixed in 9166985d82afee4923aeace243fc5e620b7bb9d8
