### ISSUE TITLE
OK Zoomer for 1.17

### ISSUE THREAD

**Issue by Minionguyjpro** [joaoh1/OkZoomer#26]
Make OK Zoomer for 1.17. Because its now released.

**Comment by EnnuiL** [comment]
1) Duplicate of #22
2) If you haven't noticed, the second 5.0.0 beta (which is for 1.17) is already work-in-progress; It was only until quite recently that problems that stopped me from working on it like a lack of a non-bloated config screen API and a lack of motivation were solved, and despite that, there's still a final roadblock to come over, and also there's still a lot to do until I can say it's ready; So, have some patience because the next beta will be released when it's done, and I'm already actively working on it

**Comment by Minionguyjpro** [comment]
does the beta also work with the now official 1.17 release?
