### ISSUE TITLE
Only zooms my hand

### ISSUE THREAD

**Issue by h3livm** [joaoh1/OkZoomer#30]
When I press C it only zooms my hand / item held and not what I'm looking at. (1.16.5)
https://user-images.githubusercontent.com/84251899/123658017-9fbea280-d831-11eb-8297-33bb431d39d9.mp4

**Comment by EnnuiL** [comment]
My first guess is that there's a mod incompatibility at the part where the FOV is calculated, and some other mod is probably modifying it in a way that completely ignores modifications from other mods. If that's the case (which I'm sure that it is), then there's nothing that I can do about it on this mod's side. I'd try to narrow down the specific mod that causes this incompatibility, however, there's no mod list

**Comment by solonovamax** [comment]
Afaik he's using the same mods as I am. (I'm the one who set him up with fabric and gave him my mods folder. @KOHIKU let me know if you added any other mods)

The only thing is, it doesn't happen in my game, but it does for him.

Here's my mods list:

### Bug Fixes Mods
- [Item model fix](https://github.com/PepperCode1/Item-Model-Fix)
- [Keep head names](https://modrinth.com/mod/keepheadnames)
- [Random Patches](https://modrinth.com/mod/randompatches)

### HUD Mods
- [Advanced Chat](https://modrinth.com/mod/advancedchat)
- [Custom HUD](https://modrinth.com/mod/customhud) (I personally have this one disabled, idk about kohi; he might have changed my config file)
- [Durability Viewer](https://modrinth.com/mod/durabilityviewer) (I have this one disabled, idk about kohi; he might have changed my config file)
- [Horse Stats](https://modrinth.com/mod/horsestatsvanilla)
- [HUDTweaks](https://modrinth.com/mod/hudtweaks)
- [InvMove](https://modrinth.com/mod/invmove-fabric)
- [MiniHUD](https://github.com/maruohon/minihud)

### Utility
- [Litematica](https://github.com/maruohon/litematica)
- [Replay Mod](https://www.replaymod.com/)
- [AFKPeace](https://modrinth.com/mod/afkpeace)
- [AntiGhost](https://modrinth.com/mod/antighost)
- [Chime](https://modrinth.com/mod/chime)
- [ClickThrough](https://modrinth.com/mod/clickthrough)
- [Fabrishot](https://modrinth.com/mod/fabrishot)
- [Flight Helper](https://modrinth.com/mod/flighthelper)
- [Flour's Various Tweaks](https://modrinth.com/mod/fvt)
- [Monsters in the Closet](https://modrinth.com/mod/monsters-in-the-closet)
- [No Strip](https://modrinth.com/mod/no-strip)
- (Obviously) OkZoomer
- [Resclone](https://modrinth.com/mod/resclone)
- [Stendhal](https://modrinth.com/mod/stendhal)
- [VTDownloader](https://modrinth.com/mod/vtdownloader)
- [World Edit](https://github.com/enginehub/WorldEdit)
- [Carpetmod](https://github.com/gnembon/fabric-carpet)
- [Item Scroller](https://github.com/maruohon/itemscroller)
- [MixinTrace](https://modrinth.com/mod/mixintrace)
- [Resource Extractor](https://modrinth.com/mod/resource_extractor)
- [Respackopts](https://modrinth.com/mod/respackopts)
- [Tweakaroo](https://github.com/maruohon/tweakeroo)
- [Fabrichax](https://github.com/pranavgade20/FabricHax) (idk if he uses this. I have it for basic utilities)
- [Wurst](https://github.com/Wurst-Imperium/Wurst7) (same as above)

### Visuals
- [ClearDespawn](https://modrinth.com/mod/cleardespawn)
- [Cr³stal](https://github.com/rebane2001/cr3stal/)
- [Falling Leaves](https://modrinth.com/mod/fallingleaves)
- [Figura](https://modrinth.com/mod/figura)
- [Illuminations](https://modrinth.com/mod/illuminations)
- [LambdaBetterGrass](https://modrinth.com/mod/lambdabettergrass)
- [LambDynamicLights](https://modrinth.com/mod/lambdynamiclights)
- [Sword Blocking](https://modrinth.com/mod/sword-blocking)
- [Vistas](https://modrinth.com/mod/vistas)
- [Visuals Overhaul](https://modrinth.com/mod/visual-overhaul)

### Performance
- [Cull Leaves](https://modrinth.com/mod/cull-leaves)
- [Enhanced Block Entities](https://modrinth.com/mod/cull-leaves)
- [Lithium](https://modrinth.com/mod/lithium)
- [Phosphor](https://modrinth.com/mod/phosphor)
- [Hydrogen](https://modrinth.com/mod/hydrogen)
- [Krypton](https://modrinth.com/mod/krypton)
- [LazyDFU](https://modrinth.com/mod/lazydfu)
- [Smooth Boot](https://modrinth.com/mod/smoothboot-fabric) (this may™ be disabled, but I forget.)
- [Sodium](https://modrinth.com/mod/sodium)
- [Sodium Extra](https://modrinth.com/mod/sodium-extra)
- [Indium](https://github.com/comp500/Indium)
- [Iris](https://github.com/IrisShaders/Iris) (I have this disabled in my config, idk about kohi.)

### QOL
- [Better Controls](https://modrinth.com/mod/better-controls) (I have this one disabled, idk about him)
- [Blur](https://modrinth.com/mod/blur-fabric)
- [Perspective Mod Redux](https://github.com/BackportProjectMC/PerspectiveModRedux)
- [Presence Footsteps](https://modrinth.com/mod/presence-footsteps)
- [Seamless Loading Screen](https://modrinth.com/mod/seamless-loading-screen)


### Dependencies for other Mods
- Fabric API
- ModMenu
- Malilib
- Cloth API
- Cloth Config

### Other
- [ThatOrThis](https://modrinth.com/mod/)


----

Yes, I know there's a lot of mods lmfao. Kohi will have to do a binary search to try and find it, since there is a LOT of them.

**Comment by solonovamax** [comment]
Actually, Flour's Various Tweaks (FVT) or Tweakaroo might have some setting that changes the FOV to make it static. Check those first.

**Comment by h3livm** [comment]
![image](https://user-images.githubusercontent.com/84251899/124559822-680cb780-de3c-11eb-8604-9d5f3c2d3e09.png)
So I realised why it wasn't working, I don't even remember turning that on
