### ISSUE TITLE
Consider rethinking the server-side component

### ISSUE THREAD

**Issue by Madis0** [joaoh1/OkZoomer#40]
Zooming is:
* first and foremost, an accessibility feature
* essentially just a keybind for setting vanilla's FOV temporarily
* near-universally accepted because of Optifine

Therefore, despite the addition of spyglasses, I think it does not make sense for servers to be able to limit it as much as you have defined now in [ZoomPackets.java](https://github.com/EnnuiL/OkZoomer/blob/1.17/src/main/java/io/github/ennuil/okzoomer/packets/ZoomPackets.java).

Instead, I suggest keeping most of the features configurable client-side and only giving the servers a way to disable options that would not be available with vanilla FOV/Optifine settings.

Namely:
* capping the zoom limits to vanilla FOV limits
  * if the user has a spyglass, allow increasing to spyglass limits multiplied by fov limits but also enforce an overlay in that case
* similar to the client-side request #16, the servers could send the requested chunks individually (ignoring overall server-side render distance)
* possibly other features Ok Zoomer provides that cannot be replicated in vanilla
* some new features that would need server support to work anyway

This way users can confidently use zoom in every server and servers that use this can be sure that users only use zoom within the vanilla limits.

**Comment by EnnuiL** [comment]
Hm, this is a complicated issue, because Ok Zoomer was simply meant as a replacement for OptiFine zoom, I don't want it to be seen as an "utility" mod that is in reality a hack or something and I don't want people to be banned over it; That's why the restrictions exist, although I've been careful to not have cosmetic features like zoom transitions be affected by them.

So far, I think most of the current packets do fit into the "Neither OptiFine nor Vanilla" camp (specially the "Force Classic Mode" one), although I could think about the "Disable Zoom" one and scrap it, i don't know, i just don't want anyone banned over this mod

The possibility for spyglass-related packets are something that I've been considering and I do want to add them, and if I do end doing something related to an increased render distance, I'll add options for the server, although I'll probably only tinker with that on 1.18 since it has the render/simulated distance split

I'll think about removing the "Disable Zoom" packet and working on new ones later

**Comment by Madis0** [comment]
I understand your concerns about the bans, but realistically it is not worth it to disable anything that Optifine can do, because I have not heard of any server that would ban Optifine itself. The scrolling feature _could seem_ like a hack, but since it only takes 3 clicks to change the FOV, it is replicable without the mod anyway, the mod only makes it a bit faster.

Thanks for considering this.

**Comment by EnnuiL** [comment]
The system was broken since Minecraft 1.20.6; I was considering trimming down the system to "Force Spyglass Restriction" since I have thought of this and yeah.. disabling zoom, zoom scrolling and such? That was silly; But well? This system was broken since Minecraft 1.20.6. Over 400k people have played a mod that had this system broken, and yet I had to deal with the shadow of this boogeyman all this time.

The paranoia can cease now, the paranoid woman's system has been removed in 10.0.0-beta.3. Let the paranoia over who's gonna take the throne begin.
