### ISSUE TITLE
Tweakeroo's freecam breaks zooming

### ISSUE THREAD

**Issue by SpacEagle17** [joaoh1/OkZoomer#48]
If possible, please make it able to zoom while in [tweakeroo](https://www.curseforge.com/minecraft/mc-mods/tweakeroo)'s free camera mode.

**Comment by kkellogg378** [comment]
Bump, still an issue in 1.21.1

**Comment by UpcraftLP** [comment]
Yeah this looks like an issue on tweakeroo's side since they completely override the FOV there.

But we'll try and work out a fix with them

**Comment by EnnuiL** [comment]
I've noticed that this is a global issue, as in: it apparently affects *all* zoom mods that does zooming in *any* way; if you do it by the proper way (modify the internal FOV), you are screwed, ~~if you do it the improper way (modify the FOV in the game options), you are screwed too, because Tweakeroo *will* override *any* zoom at all;~~ (EDIT: I was wrong because Tweakeroo uses the game options FOV as the ultimate overriding value; still, modifying the FOV option directly is not a reasonable approach and it will crash and burn in a way or another)

I had an objection to do anything about it at all on 2021 because of the questionable status of freecam; now? I believe it's time to do something about it, on the root source of everything; Expect a PR to be sent to them by the end of today

**Comment by EnnuiL** [comment]
Fixed on Tweakeroo on Minecraft 1.20.6+
