### ISSUE TITLE
[bug] Ok Zoomer breaks Continuity

### ISSUE THREAD

**Issue by isuewo** [joaoh1/OkZoomer#57]
This is probably due to [Continuity](https://modrinth.com/mod/continuity) relying on Fabric API and Ok Zoomer loading Quilt libraries but idk.

Using the latest version of everything:

- continuity 1.1.0+1.18.2
- fabric 0.47.10+1.18.2
- minecraft 1.18.2
- okzoomer 5.0.0-beta.5+1.18.2

**Comment by isuewo** [comment]
Here are two images for comparison:

![This is how it should look like](https://user-images.githubusercontent.com/53264315/158038146-99e4b0e1-086d-4587-9cfb-8aca481554af.png)
![This is how it looks like with Ok Zoomer](https://user-images.githubusercontent.com/53264315/158038172-c725e653-0795-4621-89a8-3277036ffe8c.png)
It's also reducing my fps by more than 15% actually (It's doing that with only having Ok Zoomer installed. I don't think a mod like this should cost that much performance when working correctly)

**Comment by EnnuiL** [comment]
This is indeed an incompatibility issue with Continuity expecting a Fabric API-specific detail that Quilt Standard Libraries (whose modules are used and bundled by this mod) and its Fabric API shim doesn't have.
While I've seen that Continuity won't do anything about the issue due to the wish to not have yet another update (which I do understand, I also don't want a bugfix-only beta.6 either) and due to QSL on Fabric not going to last for much longer, this issue is likely to persist and be present during the Quilt beta anyway if nothing is done about it; I'll be joining in the discussion and see what can be done

> It's also reducing my fps by more than 15% actually (It's doing that with only having Ok Zoomer installed. I don't think a mod like this should cost that much performance when working correctly)

Hm, this is the second time someone has said that, but this time, FAPI is on both screenshots; I should really investigate issue #47 and see what's wrong

**Comment by footballs-w-edits** [comment]
Can you please make it so that OK Zoomer does not utilize QSL? I want to use OK Zoomer over Logical Zoom. But for the time being, I'll have to switch over.

**Comment by EnnuiL** [comment]
> Can you please make it so that OK Zoomer does not utilize QSL? I want to use OK Zoomer over Logical Zoom. But for the time being, I'll have to switch over.

That's unfortunately easier said than done; Ok Zoomer requires the QSL Tags module for one of its features (Spyglass Dependency, which needs tags with a client-provided fallback), which Fabric API doesn't have an equivalent (at least not anymore)

I might, however, prepare a special version that doesn't use QSL, but in exchange, has the feature broken; This might not be needed though, since watching the conversation, it's possible that the QSL/Continuity issue will be solved with a pseudo-collab of sorts, and once QSL does its part, I'll have an update ready

**Comment by footballs-w-edits** [comment]
Alright thanks.

**Comment by EnnuiL** [comment]
QSL has fixed the issue on its own side with PR [#93](https://github.com/QuiltMC/quilt-standard-libraries/pull/93); A new version of Ok Zoomer with updated dependencies and other fixed bugs will come soon

**Comment by EnnuiL** [comment]
Fixed on Ok Zoomer 5.0.0-beta.6 and its updated bundled QSL
