### ISSUE TITLE
[bug] OkZoomer crashes game on zoom

### ISSUE THREAD

**Issue by witheredwojak** [joaoh1/OkZoomer#62]
Version: beta.5 for 1.18.2
Here is crash-report: https://crashy.net/jn52nXDJnC9Vu1zBaNjs

**Comment by EnnuiL** [comment]
This is definitely a conflict issue between LibZoomer and another mod, which possibly uses a mixin that isn't mod-compatible. My primary suspect is the "Better Third Person" mod, although since it's ARR, I can't confirm it myself
In an attempt to clear up my own mixins, I think I got [a version of LibZoomer](https://github.com/EnnuiL/LibZoomer/suites/5804892794/artifacts/194093521) that should avoid those crashes; However, this still means that there's an another mod with a mod-unfriendly mixin, and while I probably managed to accidentally find a way around that, it's not always that something can be done about that
So, yeah, try it out and see if the issue's solved; If it doesn't, then yeah, there isn't anything that I can do about the issue
