### ISSUE TITLE
1.19.3?

### ISSUE THREAD

**Issue by RoonMoonlight** [joaoh1/OkZoomer#90]
Hey OkZoomer devs! Glad this mod is now Quilt-based. Can you update this mod for 1.19.3 on Modrinth/CurseForge if you can?

**Comment by EnnuiL** [comment]
Hello; Progress has already started on the 1.19.3 branch, and it might be close to a release! Unfortunately, a feature (spyglass dependencies) has been broken on QSL's side (see issue [#235](https://github.com/QuiltMC/quilt-standard-libraries/issues/235)) and the affected area is out of my expertise;

A build artifact is available [here](https://github.com/EnnuiL/OkZoomer/suites/9928038024/artifacts/480380821); Although yeah, I may have to consider releasing the build as-is with it marked as an alpha because yeah, it'll perhaps take a while until it's fixed (the relevant dev has been pretty busy and i don't wanna make things worse); But once fixed on QSL's side, all I'll have to do is mark it as stable once again

**Comment by EnnuiL** [comment]
I've went with a workaround for now, which yeah, should be enough; Another update will be released once the QSL issue has been fixed
