### ISSUE TITLE
Performance while zoomed in

### ISSUE THREAD

**Issue by Mathmagician8191** [joaoh1/OkZoomer#92]
When using this mod to zoom in, the framerate does not increase.

However, when changing the FOV from 110 to 30, the FPS goes up by a lot (presumably due to culling parts of the world that are offscreen).

This behaviour occurs both with and without sodium being installed.

Is there a way to make the game get an accurate FOV value and apply more culling?

**Comment by EnnuiL** [comment]
Hm, this explains why there hasn't been a need to refresh the terrain when zooming out anymore; I might end tackling this once I redesign the entire mod

**Comment by EnnuiL** [comment]
Good news! It turns out I can do the same shenanigans I did on the old times (although with slightly more effort needed than "just zoom"), but I do want to make sure this has no negative impact;
I will test this tomorrow on my laptop, and also see if this won't conflict with Sodium (I hope not!); If all works out? The next Ok Zoomer 10.0.0 beta will download free FPS on your system :p

**Comment by EnnuiL** [comment]
Fixed on Ok Zoomer 10.0.0-beta.4
