### ISSUE TITLE
Zoom Presets do not work

### ISSUE THREAD

**Issue by stantios** [joaoh1/OkZoomer#93]
Mod Version: 5.0.0-beta.10 and beta.9
Game Version: 1.19.2 and 1.19.3

Description: I tried to use on of the presets on the mod like, Classic or Persistent. But when I applied them, it didn't save and kept going back to the default preset.

Steps to reproduce:

1. Open OkZoomer's Configuration
2. Change the preset to anything and click done
3. Go back to the game and test the zoom
4. You've found the bug!

**Comment by EnnuiL** [comment]
As discussed on Discord ages ago, it isn't a bug, but rather, this is part of a common pattern that comes with the way the config screen currently works: people press <kbd>ESC</kbd> and expect the config to be saved, like the Minecraft ones, but it intentionally doesn't; Therefore, this is user error, but it is user error caused by a design flaw on our config screen;
I plan to tackle this once I tackle a redesigned config screen for this mod (this mod? maybe all mods that quilt config; i have plans :p)
