### ISSUE TITLE
Crash with OK Zoomer 5.0.0 on Minecraft 1.20.1

### ISSUE THREAD

**Issue by whitebear60** [joaoh1/OkZoomer#99]
After the update to Quilt 0.22.0 and OK Zoomer 5.0.0 (which were marked compatible when launching on 0.21.2), Minecraft doesn't launch, requiring mixinextras, which aren't on Modrinth (from what I see, they should be bundled with Quilt, but, looks like, they don't)

<img width="400" alt="image" src="https://github.com/EnnuiL/OkZoomer/assets/42472132/de74824c-0c45-4c2d-abca-acef03a92708">

<img width="400" alt="image" src="https://github.com/EnnuiL/OkZoomer/assets/42472132/e6ecf8e4-742b-46f5-97e7-ebb07d1e1e37">

Crash log: https://mclo.gs/HUviHU2

**Comment by EnnuiL** [comment]
The problem here is that the actual required Quilt Loader version is 0.23.0 (with 0.22.1-beta.4 working as well), which only have betas so far; If it's possible to update to the 0.23.0 betas, do try that! but if you can't? Well, it's complicated, because the alternative solution that I wanted to propose (and the reason why I didn't enforce a QLoader 0.23.0 dependency) was "install MixinExtras separately", but its Fabric Loader requirement is slightly above the one provided by the latest non-beta release (0.22.0), which makes manual editing required and aughhhhh

The solution is to either update to the Quilt Loader 0.23.0 betas (0.23.0-beta.1 as of time of writing) or downgrade to Ok Zoomer 5.0.0-beta.13; I'll consider bumping the Loader requirement in order to make that clear, since the workaround I had in mind uh, doesn't really work

**Comment by whitebear60** [comment]
I updated to the beta but decided to file a report nonetheless cause the specified loader requirement isn't correct still
________________________________

**Comment by EnnuiL** [comment]
Addressed on Ok Zoomer 5.0.1
